### ISSUE TITLE
Deploy failing, can't find subscription, even though there's two in the account

### ISSUE THREAD

**Issue by wsrast** [serverless/serverless-azure-functions#107]
After successfully signing in through the interactive process in the browser, I'm getting this error:

Error --------------------------------------------------

  There aren't any subscriptions associated with this Azure account

I've opened portal.azure.com and verified that my MSDN account has two subscriptions associated with it, and the directory appears to be correctly set. Is anyone else having issues with this?

Also, the login process takes a looooong time; around 10 minutes per attempt.

Could this be related to running behind a corporate firewall? Are there proxy settings to concern myself with inside serverless.js?

Here's the full trace after turning on the debug env variable:

Error: There aren't any subscriptions associated with this Azure account
    at Promise (C:\Users\rastwe\dev\serverless\test-service\node_modules\az-login\index.js:196:27)
    at new Promise (<anonymous>)
    at resolveSubscription (C:\Users\rastwe\dev\serverless\test-service\node_modules\az-login\index.js:192:12)
    at authenticate.then (C:\Users\rastwe\dev\serverless\test-service\node_modules\az-login\index.js:250:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
From previous event:
    at PluginManager.invoke (C:\Users\rastwe\AppData\Roaming\nvm\v8.9.4\node_modules\serverless\lib\classes\PluginManager.js:368:22)
    at PluginManager.run (C:\Users\rastwe\AppData\Roaming\nvm\v8.9.4\node_modules\serverless\lib\classes\PluginManager.js:399:17)
    at variables.populateService.then (C:\Users\rastwe\AppData\Roaming\nvm\v8.9.4\node_modules\serverless\lib\Serverless.js:102:33)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Serverless.run (C:\Users\rastwe\AppData\Roaming\nvm\v8.9.4\node_modules\serverless\lib\Serverless.js:89:74)
    at serverless.init.then (C:\Users\rastwe\AppData\Roaming\nvm\v8.9.4\node_modules\serverless\bin\serverless:42:50)
    at <anonymous>

**Comment by rupakg** [comment]
> Could this be related to running behind a corporate firewall? Are there proxy settings to concern myself with inside serverless.js?
@wsrast Have you tried without the firewall? Trying to narrow down the problem.
