### ISSUE TITLE
Getting error 'socket hang up' while deploying Azure

### ISSUE THREAD

**Issue by r0B-O** [serverless/serverless-azure-functions#135]
I get the following error while I deploy nodejs function to azure. With SET_DEBUG=true, I get the following. This is specific for azure, because sls deploys functions to AWS.

`Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Building Azure Events Hooks
Serverless: Parsing Azure Functions Bindings.json...
Serverless: Building binding for function: hello event: httpTrigger
Serverless: Building binding for function: hello event: http
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Logging in to Azure
Serverless: Looking for deployed functions that are not part of the current deployment...
Serverless: Creating resource group: adOps-rg
Serverless: Creating function app: adOps
Serverless: Waiting for Kudu endpoint...
Serverless: Uploading function: hello
 
  Error --------------------------------------------------
 
  socket hang up
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at TLSSocket.socketOnEnd (_http_client.js:426:23)
    at TLSSocket.emit (events.js:194:15)
    at TLSSocket.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:422:17)
    at variables.populateService.then.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:44:28)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           10.15.3
     Serverless Version:     1.35.1`

**Comment by tbarlow12** [comment]
Looks like this was using `v0`. Please try updating your version and let us know if you experience the same thing. Closing for now
