### ISSUE TITLE
sls offline crashes with 'spawn func ENOENT'

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless-azure-functions#259]
I wanted to try `sls offline` still it crashes with:

```
$ sls offline
Serverless: Building offline service
Serverless: Parsing Azure Functions Bindings.json...
Serverless: Building binding for function: hello event: httpTrigger
Serverless: Building binding for function: hello event: http
Serverless: Parsing Azure Functions Bindings.json...
Serverless: Building binding for function: goodbye event: httpTrigger
Serverless: Building binding for function: goodbye event: http
Serverless: Finished building offline service
Serverless: Spawning process 'func host start'
 
  Error --------------------------------------------------
 
  Error: spawn func ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.8.1
     Framework Version:         1.50.0
     Plugin Version:            1.3.8
     SDK Version:               2.1.0
```

**Comment by tbarlow12** [comment]
@medikoo do you have `azure-functions-core-tools` installed globally?

**Comment by medikoo** [comment]
> @medikoo do you have azure-functions-core-tools installed globally?

No, is it needed for `sls offline`?

**Comment by medikoo** [comment]
If it's a dependency of a plugin (to support `offline` command). I believe it should be listed as one in `package.json`

Then also it'll be better to invoke it programmatically (instead of relying on `spawn`), and if for some reason it has to go via `spawn`, I think we should not demand `azure-functions-core-tools` to be installed globally, but instead reach for binary installed as a local dependency.
