### ISSUE TITLE
DNS error when deleting and then recreating function app

### ISSUE THREAD

**Issue by mgarrettm** [serverless/serverless-azure-functions#30]
I've been seeing this error sporadically when deleting and then immediately recreating a function app:

```
Serverless: Logging in to Azure
Serverless: Deleting deployment: <service-name>-rg-deployment
Serverless: Deleting resource group: <service-name>-rg
Serverless: Service successfully removed
Serverless: Packaging service...
Serverless: Logging in to Azure
Serverless: Creating resource group: <service-name>-rg
Serverless: Creating function app: <service-name>
Serverless: Waiting for Kudu endpoint...
Serverless: Parsing Azure Functions Bindings.json...
Serverless: Building binding for function: <function-name> event: httpTrigger
Serverless: Packaging function: <function-name>

  Error --------------------------------------------------

     getaddrinfo ENOTFOUND <service-name>.scm.azurewebsites.net
     <service-name>.scm.azurewebsites.net:443

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: getaddrinfo ENOTFOUND <service-name>.scm.azurewebsites.net <service-name>.scm.azurewebsites.net:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
From previous event:
    at PluginManager.run (/home/ubuntu/node_modules/serverless/lib/classes/PluginManager.js:160:22)
    at Serverless.run (/home/ubuntu/node_modules/serverless/lib/Serverless.js:91:31)
    at serverless.init.then (/home/ubuntu/node_modules/serverless/bin/serverless:23:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       6.9.5
     Serverless Version: 1.7.0
```

It seems like it might be an issue with DNS caching in Antares or Kudu after the deletion, but I'm not sure. Do you have any idea what this is, and/or is there a better way to handle existence checking here?

**Comment by pragnagopa** [comment]
Yes. This is a known issue with DNS resolution in Antares.  Looks like we now have a consistent repro. Will follow up on this.

**Comment by sevetseh28** [comment]
Could you resolve this issue in the end? Thank you
