### ISSUE TITLE
Listing Deployments: TypeError: Cannot convert undefined or null to object error

### ISSUE THREAD

**Issue by bstorrie** [serverless/serverless-azure-functions#410]
# This is a Bug Report

## Description

When attempting to deploy to Azure I'm getting a TypeError when the plugin is checking previous deployment templates.

```
TypeError: Cannot convert undefined or null to object
      at Function.keys (<anonymous>)
      at paramsNormalizer (/Users/brucestorrie/drds/azuretest/drdsfuncs/node_modules/serverless-azure-functions/lib/services/armService.js:259:31)
      at ArmService.areDeploymentsEqual (/Users/brucestorrie/drds/azuretest/drdsfuncs/node_modules/serverless-azure-functions/lib/services/armService.js:276:80)
      at ArmService.<anonymous> (/Users/brucestorrie/drds/azuretest/drdsfuncs/node_modules/serverless-azure-functions/lib/services/armService.js:193:34)
      at step (/Users/brucestorrie/drds/azuretest/drdsfuncs/node_modules/serverless-azure-functions/lib/services/armService.js:56:23)

```

## Additional Data

I've debugged the issue and identified that it's because the previous deployment template did not contain any parameters but there is a check within the code to compare templates which isn't catering for that scenario.

**Comment by miguel-a-calles-mba** [comment]
I'm seeing this. I keep having to remove and re-deploy to make updates.

Can we get this PR merged? https://github.com/serverless/serverless-azure-functions/pull/411

**Comment by gilmarp** [comment]
I'm having that too. The workaround prevent us to do rollbacks as we have to remove before deploy.

**Comment by andidev** [comment]
When will this be released?

**Comment by zsolt-halo** [comment]
please release this :) it would make things much smoother

**Comment by andidev** [comment]
@zsolt-halo 
There is actually a pre-release with this fix. You can use
```
"serverless-azure-functions": "1.0.2-19",
```

**Comment by zsolt-halo** [comment]
@andidev 
I have tested it and it indeed solved the problem, thank you very much for bringing this to my attention.

**Comment by FirstInternetUser** [comment]
@miguel-a-calles-mba removing the deployment and re-deploying resolved the issue for me too.

**Comment by Rapol** [comment]
We are having this issue during deploy on and off and we don't how we get into this state.

```
Serverless: Listing deployments for resource group '...':
 
  Type Error ---------------------------------------------
 
  TypeError: Cannot convert undefined or null to object
      at Function.keys (<anonymous>)
      at paramsNormalizer (/builds/cloudresdev/connect-backend/notifications/node_modules/serverless-azure-functions/lib/services/armService.js:259:31)
      at ArmService.areDeploymentsEqual (/builds/cloudresdev/connect-backend/notifications/node_modules/serverless-azure-functions/lib/services/armService.js:276:80)
      at ArmService.<anonymous> (/builds/cloudresdev/connect-backend/notifications/node_modules/serverless-azure-functions/lib/services/armService.js:193:34)
      at step (/builds/cloudresdev/connect-backend/notifications/node_modules/serverless-azure-functions/lib/services/armService.js:56:23)
      at Object.next (/builds/cloudresdev/connect-backend/notifications/node_modules/serverless-azure-functions/lib/services/armService.js:37:53)
      at fulfilled (/builds/cloudresdev/connect-backend/notifications/node_modules/serverless-azure-functions/lib/services/armService.js:28:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:94:5)
  From previous event:
      at PluginManager.invoke (/builds/cloudresdev/connect-backend/notifications/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at /builds/cloudresdev/connect-backend/notifications/node_modules/serverless/lib/classes/PluginManager.js:525:24
  From previous event:
      at PluginManager.run (/builds/cloudresdev/connect-backend/notifications/node_modules/serverless/lib/classes/PluginManager.js:525:8)
      at /builds/cloudresdev/connect-backend/notifications/node_modules/serverless/lib/Serverless.js:132:33
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)
  From previous event:
      at Serverless.run (/builds/cloudresdev/connect-backend/notifications/node_modules/serverless/lib/Serverless.js:119:74)
      at /builds/cloudresdev/connect-backend/notifications/node_modules/serverless/bin/serverless.js:74:30
      at /builds/cloudresdev/connect-backend/notifications/node_modules/graceful-fs/graceful-fs.js:111:16
      at /builds/cloudresdev/connect-backend/notifications/node_modules/graceful-fs/graceful-fs.js:45:10
      at FSReqCallback.oncomplete (fs.js:146:23)
  From previous event:
      at /builds/cloudresdev/connect-backend/notifications/node_modules/serverless/bin/serverless.js:74:8
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)
  From previous event:
      at Object.<anonymous> (/builds/cloudresdev/connect-backend/notifications/node_modules/serverless/bin/serverless.js:63:4)
      at Module._compile (internal/modules/cjs/loader.js:955:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
      at Module.load (internal/modules/cjs/loader.js:811:32)
      at Function.Module._load (internal/modules/cjs/loader.js:723:14)
      at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
      at internal/main/run_main_module.js:17:11
```

After this happens there is no way of deploying without making this fix in armService.ts:

```
 private areDeploymentsEqual(current: ArmDeployment, previous: ArmDeployment): boolean {
    if (!current || !previous
   || !previous.template || !previous.parameters      <--- add these two conditions
) {
      return false;
    }
```
