### ISSUE TITLE
Cannot set property 'name' of undefined Python timer

### ISSUE THREAD

**Issue by jeicob22** [serverless/serverless-azure-functions#444]
# This is a Bug Report

## Description

- What went wrong?
Error when running  "sls offline" and "sls deploy" for deploying a Python 3.7 Function with a "timer" event.

- What did you expect should have happened?
To Successfully deploy the timer/cron

- What was the config you used?
```yaml
service: megatest-num2

provider:
  name: azure
  location: West Europe
  region: westeurope
  runtime: "python3.7"
  os: "linux"
  resourceGroup: my-mega-test-rg
  storageAccount:
    httpsTrafficOnly: true

plugins: # look for additional plugins in the community plugins repo: https://github.com/serverless/plugins
  - serverless-azure-functions

# you can add packaging information here
package:
  include:
    - src/shared/**
  exclude:
    - local.settings.json
    - .vscode/**

functions:
  SyncDirUsers:
    handler: "src/handlers/SyncDirUsers.main"
    events:
      - timer: true
        x-azure-settings:
          name: myCron
          schedule: '* */10 * * * *'
```
src/handlers/SyncDirUsers.main

```python
import azure.functions as func
import logging

def main(mytimer: func.TimerRequest) -> None:
    logging.info('Python received a cron trigger.')
```

- What stacktrace or error message from your provider did you see?
```bash
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command remove
Serverless: Load command deploy
Serverless: Load command deploy:list
Serverless: Load command deploy:apim
Serverless: Load command func
Serverless: Load command func:add
Serverless: Load command func:remove
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command offline:build
Serverless: Load command offline:cleanup
Serverless: Load command rollback
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command dev
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Initializing provider configuration...
Serverless: Parsing Azure Functions Bindings.json...
Serverless: Building binding for function: SyncDirUsers event: timerTrigger
 
  Type Error ---------------------------------------------
 
  TypeError: Cannot set property 'name' of undefined
      at PackageService.getFunctionJson (/home/juribe/Documents/test-projects/azure-serverless/megatest-num2/.serverless_plugins/serverless-azure-functions/lib/services/packageService.js:214:47)
      at PackageService.createBinding (/home/juribe/Documents/test-projects/azure-serverless/megatest-num2/.serverless_plugins/serverless-azure-functions/lib/services/packageService.js:202:33)
      at PackageService.<anonymous> (/home/juribe/Documents/test-projects/azure-serverless/megatest-num2/.serverless_plugins/serverless-azure-functions/lib/services/packageService.js:102:68)
      at step (/home/juribe/Documents/test-projects/azure-serverless/megatest-num2/.serverless_plugins/serverless-azure-functions/lib/services/packageService.js:45:23)
      at Object.next (/home/juribe/Documents/test-projects/azure-serverless/megatest-num2/.serverless_plugins/serverless-azure-functions/lib/services/packageService.js:26:53)
      at fulfilled (/home/juribe/Documents/test-projects/azure-serverless/megatest-num2/.serverless_plugins/serverless-azure-functions/lib/services/packageService.js:17:58)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From previous event:
      at PluginManager.invoke (/snapshot/serverless/lib/classes/PluginManager.js:490:22)
      at PluginManager.spawn (/snapshot/serverless/lib/classes/PluginManager.js:510:17)
      at Deploy.<anonymous> (/snapshot/serverless/lib/plugins/deploy/deploy.js:115:50)
  From previous event:
      at Object.before:deploy:deploy [as hook] (/snapshot/serverless/lib/plugins/deploy/deploy.js:100:30)
      at /snapshot/serverless/lib/classes/PluginManager.js:490:55
  From previous event:
      at PluginManager.invoke (/snapshot/serverless/lib/classes/PluginManager.js:490:22)
      at /snapshot/serverless/lib/classes/PluginManager.js:525:24
  From previous event:
      at PluginManager.run (/snapshot/serverless/lib/classes/PluginManager.js:525:8)
      at /snapshot/serverless/lib/Serverless.js:133:33
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Serverless.run (/snapshot/serverless/lib/Serverless.js:120:74)
      at /snapshot/serverless/bin/serverless.js:82:30
      at /snapshot/serverless/node_modules/graceful-fs/graceful-fs.js:144:16
      at /snapshot/serverless/node_modules/graceful-fs/graceful-fs.js:65:14
      at FSReqCallback.oncomplete (fs.js:154:23)
  From previous event:
      at /snapshot/serverless/bin/serverless.js:82:8
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Object.<anonymous> (/snapshot/serverless/bin/serverless.js:71:4)
      at Module._compile (pkg/prelude/bootstrap.js:1324:22)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
      at Module.load (internal/modules/cjs/loader.js:1000:32)
      at Function.Module._load (internal/modules/cjs/loader.js:899:14)
      at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
      at internal/main/run_main_module.js:18:47
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.16.1
     Framework Version:         1.67.3 (standalone)
     Plugin Version:            3.6.6
     SDK Version:               2.3.0
     Components Version:        2.29.0
```
Similar or dependent issues:

- #12345

## Additional Data

- **_Serverless Framework Version you're using_**: 1.67.3 
- **_Serverless CLI Version you're using_**: 1.67.3 
- **_Serverless Azure Plugin Version you're using_**: v1.0.2-27
- **_Operating System_**: Ubuntu 18.04
- **_Stack Trace_**:
- **_Provider Error messages_**:

**Comment by okelet** [comment]
@jeicob22 have you found any workaround?
