### ISSUE TITLE
login hangs

### ISSUE THREAD

**Issue by Stewartarmbrecht** [serverless/serverless-azure-functions#80]
Whenever I run serverless deploy the deploy hangs after I login to azure

`Serverless: Packaging service...
Serverless: Logging in to Azure
Serverless: Paste this code (copied to your clipboard) into the launched browser, and complete the authentication process: FM6YDF4DS`

I am prompted to login in Chrome and chrome shows
"Microsoft Azure Cross-platform Command Line Interface
You have signed in to the Microsoft Azure Cross-platform Command Line Interface application on your device. You may now close this window."

When I return to either Windows Command Prompt or Powershell the print out has not changed.  The cursor is still sitting after:

Serverless: Paste this code (copied to your clipboard) into the launched browser, and complete the authentication process: FM6YDF4DS

I am running Windows 10
Serverless: 1.17.0
Node: 6.11.0
npm: 5.2.0
serverless-azure-functions: 0.2.0

I have tried to add the service principle credentials but I get this error as well even through the credentials are correct:

Serverless: Packaging service...
Serverless: Logging in to Azure

  Type Error ---------------------------------------------

  Cannot read property 'tokenCache' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'tokenCache' of undefined
    at authenticate.then (C:\Users\Stewart\Source\Repos\tococms\architect\tococms-api\node_modules\serverless-azure-functions\node_modules\az-login\index.js:209:40)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
From previous event:
    at PluginManager.invoke (C:\Users\Stewart\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:217:22)
    at PluginManager.run (C:\Users\Stewart\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:236:17)
    at variables.populateService.then (C:\Users\Stewart\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:107:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (C:\Users\Stewart\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:94:74)
    at serverless.init.then (C:\Users\Stewart\AppData\Roaming\npm\node_modules\serverless\bin\serverless:32:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           6.11.0
     Serverless Version:     1.17.0

I ran this before hand

set azureSubId='my value removed'
set azureServicePrincipalTenantId='my value removed'
set azureServicePrincipalClientId='my value removed' 
set azureServicePrincipalPassword='my value removed'

**Comment by lostintangent** [comment]
This issue should now be resolved if you update to the latest Serverless-Azure-Functions module. Please reopen this if you're still experiencing a login problem. Thanks!
