### ISSUE TITLE
`serverless deploy` and `serverless verify` failing on Azure

### ISSUE THREAD

**Issue by arunshan** [serverless/serverless-azure-functions#91]
# This is a Bug Report

## Description
`serverless deploy` all of a sudden started throwing the following error on Azure deployments.

```
Long running operation failed with error: "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.".
```

Complete Stack Trace:

```
Error: Long running operation failed with error: "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.".
    at PollingState.getCloudError (/Users/arunshankar/layer/integrations/test-azure/node_modules/ms-rest-azure/lib/pollingState.js:127:17)
    at /Users/arunshankar/layer/integrations/test-azure/node_modules/ms-rest-azure/lib/azureServiceClient.js:157:38
    at /Users/arunshankar/layer/integrations/test-azure/node_modules/async/dist/async.js:906:16
    at next (/Users/arunshankar/layer/integrations/test-azure/node_modules/async/dist/async.js:5198:18)
    at /Users/arunshankar/layer/integrations/test-azure/node_modules/ms-rest-azure/lib/azureServiceClient.js:130:20
    at _getStatus (/Users/arunshankar/layer/integrations/test-azure/node_modules/ms-rest-azure/lib/azureServiceClient.js:184:5)
    at /Users/arunshankar/layer/integrations/test-azure/node_modules/ms-rest-azure/lib/azureServiceClient.js:322:12
    at retryCallback (/Users/arunshankar/layer/integrations/test-azure/node_modules/ms-rest/lib/filters/systemErrorRetryPolicyFilter.js:89:9)
    at retryCallback (/Users/arunshankar/layer/integrations/test-azure/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (/Users/arunshankar/layer/integrations/test-azure/node_modules/ms-rest/lib/filters/redirectFilter.js:39:9)
    at /Users/arunshankar/layer/integrations/test-azure/node_modules/ms-rest-azure/lib/filters/rpRegistrationFilter.js:59:14
    at Request.defaultRequest [as _callback] (/Users/arunshankar/layer/integrations/test-azure/node_modules/ms-rest/lib/requestPipeline.js:125:16)
    at Request.self.callback (/Users/arunshankar/layer/integrations/test-azure/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/arunshankar/layer/integrations/test-azure/node_modules/request/request.js:1171:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/arunshankar/layer/integrations/test-azure/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
From previous event:
    at PluginManager.invoke (/Users/arunshankar/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:358:22)
    at PluginManager.run (/Users/arunshankar/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:389:17)
    at variables.populateService.then (/Users/arunshankar/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Serverless.run (/Users/arunshankar/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/Users/arunshankar/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/bin/serverless:39:50)
```

`serverless verify -f <function_name> -t` returns an error as well on Azure.

```
  Error --------------------------------------------------
 
  [object Object]
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: [object Object]
    at module.exports.logError.errorHandlingError (/Users/arunshankar/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/lib/classes/Error.js:94:11)
    at initializeErrorReporter.then.catch.e (/Users/arunshankar/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/bin/serverless:42:3)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at __dirname (/Users/arunshankar/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/bin/serverless:40:9)
    at Object.<anonymous> (/Users/arunshankar/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/bin/serverless:43:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

When diving deeper into the error message, we see that the log error is because of the following:

```
{ Message: 'An error has occurred.',
  ExceptionMessage: 'unable to decrypt CfDJsomekeyhereAAAAAAAAAC3heQ-ij-6Pm4kdEjSLzoOpIknaIrnqjrdSXzP2ZuVK0Tz8BzE05Vt1AgIpNjXeDc_5Rsfc338xOQZxBzMzEIXBTZNcCvOUIWa_itNVZ_UMIlCAK4s56LF6EYf_aH3E_TF9YYIQbEIxwTTMKO7-xkI-aAHaI8YE_vI6oHmDfizNw, the key is either invalid or malformed',
  ExceptionType: 'System.FormatException',
```

**Comment by thewtex** [comment]
I am also observing this behavior. This occurs after

```
Serverless: Creating function app: serverless-name
```

**Comment by Mauzer93** [comment]
I had the same problem and was able to solve it by deleting the corresponding file share of that particular Azure Function.

**Comment by qs-wang** [comment]
Save issue, did nothing, and it was recovered by itself.

**Comment by qs-wang** [comment]
Actually this type of error is the general message which indicates there's something wrong at azure side. Had to go to azure portal to figure out what's wrong.

**Comment by ndarilek** [comment]
Still hitting this today. I don't mean to seem snarky, but does this plugin even still work, and is this maintained? I couldn't even log in without creating a ~/.azure directory.

**Comment by WendySanarwanto** [comment]
+1 It sill happen with serverless version 1.26 , node.js 9.5 , ran in windows 10

**Comment by stayRestful** [comment]
I had this same issue and [this thread](https://github.com/serverless/serverless-azure-functions/issues/40) resolved it for me.

**Comment by rlgod** [comment]
Yeh this ended up being because my service name wasn't globally unique. I was trying to use `url-shortener` and it was just giving that useless error. Added a prefix and it all worked fine.

**Comment by mrc0260** [comment]
I had the same issue but I resolved in a different way, I just opened the file serverless.yml and on line 14 
"service: myservicename # NOTE: update this with your service name"
I just changed myservicename with a new name, and it works

**Comment by tbarlow12** [comment]
Looks like this was using `v0`. Please try updating your version and let us know if you experience the same thing. Closing for now
