### ISSUE TITLE
serverless deploy fails - Error executing command, try again later

### ISSUE THREAD

**Issue by mhaggerty042** [serverless/serverless-azure-functions#94]
Hi,

Serverless deploy will sometimes fail with **Error executing command, try again later**. Usually when I try again later, it works after 15 min or so. However, waiting no longer seems to resolve the issue.

```
Serverless: Syncing Triggers....Response statuscode: 200
Serverless: Running Kudu command del package.json...
Serverless: Uploading pacakge.json...
Serverless: Running Kudu command npm install --production...
 
  Error --------------------------------------------------
 
  Error executing command, try again later.
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: Error executing command, try again later.
    at module.exports.logError (/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/node8.9/lib/node_modules/serverless/lib/classes/Error.js:94:11)
    at initializeErrorReporter.then.catch.e (/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/node8.9/lib/node_modules/serverless/bin/serverless:42:3)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at __dirname (/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/node8.9/lib/node_modules/serverless/bin/serverless:40:9)
    at Object.<anonymous> (/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/node8.9/lib/node_modules/serverless/bin/serverless:43:4)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.9.0
     Serverless Version:     1.23.0
```

**Comment by rupakg** [comment]
@mhaggerty042 are you deploy as part of a CI setup?

**Comment by iredjee** [comment]
I also face such kind of issue. Deploying from my local machine

**Comment by tomaustin700** [comment]
Also getting the same issue when deploying from a local machine

**Comment by jamesdixon** [comment]
anyone have any luck solving this?
